### ISSUE TITLE
1.6.6 segfaults on first `lex()` under Node < 22.21.0 / < 24.9.0 (unbound `node_api_is_sharedarraybuffer`)

### ISSUE THREAD

**Issue by claudiovb** [holepunchto/bare-module-lexer#43]
## Symptom

`require()` succeeds, the first `lex()` call crashes the process with SIGSEGV (exit 139). 1.6.5 works on the same Node. Observed on macOS arm64; the Linux and Windows prebuilds carry the same unresolved import (see below) but I have not run them.

```sh
npm i bare-module-lexer@1.6.6
node -e 'require("bare-module-lexer")(Buffer.from("module.exports = require(\"x\")"))'
# exit 139 on Node 22.13.1, 23.10.0, 24.8.0; works on 24.21.0
```

lldb: `EXC_BAD_ACCESS (address=0x0)`, frame 1 is `bare_module_lexer.node\`bare_module_lexer_lex + 108`.

## Cause

#40 (7d5560d) added `js_is_sharedarraybuffer()` to `bare_module_lexer_lex` (binding.c:257) and `NAPI_EXPERIMENTAL` to the Node-API target (CMakeLists.txt:29). Through bare-compat-napi (include/js.h:1080) that maps to `node_api_is_sharedarraybuffer`, a Stability 1 symbol that Node only exports since v24.9.0 and v22.21.0 (nodejs/node#59071). It is guarded by `NAPI_EXPERIMENTAL`, not by `NAPI_VERSION`, so `process.versions.napi` is 10 on both 24.8 and 24.21 and cannot tell the hosts apart.

The prebuilds are linked with `-undefined dynamic_lookup` (cmake-napi), so the import stays unresolved until load time:

```sh
nm -u prebuilds/darwin-arm64/bare-module-lexer.node | grep shared
_node_api_is_sharedarraybuffer      # present in 1.6.6, absent in 1.6.5
```

On a macOS host without the export, dyld binds the symbol to 0 and the call at binding.c:257 jumps to address 0 on every input, including plain `ArrayBuffer`s. `nm -u` on the linux-x64 prebuild and `strings` on win32-x64 show the same import, so those platforms are presumably affected as well, but that is untested.

CI does not catch it because holepunchto/actions installs a current Node. Any lockfile that resolves `bare-module-traverse >= 2.5` (lexer `^1.6.0`) picks up 1.6.6, so `bare-pack` dies with it on those hosts.

## Fix options

1. **Weak-link the experimental symbol.** Declare `node_api_is_sharedarraybuffer` as a weak reference in the Node-API build and treat a NULL address as "not a SharedArrayBuffer". Hosts that export the symbol (Node 24.21.0, for example) get full SharedArrayBuffer support; older hosts keep lexing ordinary buffers and get the 1.6.5 `TypeError: Input must be a buffer` for shared input. We think this is the stronger option for a module that targets both Bare and Node: the feature stays available where the host has it, and the module stays usable on the Node versions most people still run instead of crashing on every input. Verified on macOS arm64 with a local clang build: 185/185 tests on Node 24.21.0 and under Bare 1.32.0, no crash and correct plain-buffer output on Node 22.13.1 and 24.8.0. The same change could live in bare-compat-napi's `js_is_sharedarraybuffer` so every addon using the shim benefits. Not tested on Linux or Windows; Windows would need a different mechanism than a weak reference since MSVC has none.

2. **Gate on `engines`.** #42 already adds `engines.node = "^22.21.0 || >=24.9.0"`, but it is unpublished (latest is still 1.6.6), and npm only prints `EBADENGINE` as a warning and installs anyway, so on its own it does not prevent the crash. Still useful as documentation of the SharedArrayBuffer feature floor alongside option 1.

**Comment by kasperisager** [comment]
We only support Node.js LTS releases which all have the required API. I'll publish the `"engines"` requirement introduced in #42.
